
test_rx_handler:
	gcc test_rx_handler.c ../src/sscp.c -o test_rx_handler

test_encode_and_decode:
	gcc test_encode_and_decode.c ../src/sscp.c -o test_encode_and_decode

clean:
	rm test_rx_handler.exe