
test_rx_handler:
	gcc test_rx_handler.c ../src/sscp.c -o test_rx_handler

test_encode_and_decode:
	gcc test_encode_and_decode.c ../src/sscp.c -o test_encode_and_decode

test_sscp_responder:
	gcc test_sscp_responder.c ../src/sscp.c -o test_sscp_responder

clean:
	rm test_rx_handler.exe